apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-test-consumer-deployment
  labels:
    app: kafka-test-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-test-consumer
  template:
    metadata:
      labels:
        app: kafka-test-consumer
    spec:
      containers:
      - name: kafka-test-consumer
        image: rosswhitehead/kafka-test-consumer:1.3.0
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        - name: BOOTSTRAP_SERVERS
          value: 'my-cluster-kafka-bootstrap.kafka-test.svc.cluster.local:9092'
        - name: TOPIC
          value: kafka_test_topic
        - name: PARTITIONS
          value: '1'
        - name: REPLICATION_FACTOR
          value: '1'
        - name: PORT
          value: '4000'